### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by jorgegonzalez** [lirantal/create-node-app#1]
I ask because I see that you are the publisher of the create-node-app module on NPM, and it is a shame that such a name is reserved for an empty project.

**Comment by lirantal** [comment]
it's been a while since I opened the repo with the idea of creating a similar tool to `create-react-app` and my intention was to base it on my Riess.js project (https://github.com/lirantal/Riess.js) and sadly I haven't got around to it.

I've exchanged some words with someone also interested to join the project and push the work forward. If you're also interested to collaborate I'd be more than happy to add you to the project and we can kick start it again.
